version: 2.1
jobs:
  checkout:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  remove-refs:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Remove Project Refs"
          command: |
            cd src/Chex.Testing
            dotnet remove reference ../Chex/Chex.csproj
            cd ../Chex.Testing.Xunit
            dotnet remove reference ../Chex/ChexTesting.csproj
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - .
  pack-and-publish:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    parameters:
      suffix :
        type:  string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Add Artifactory to Nuget Sources"
          command: dotnet nuget add source https://mathtone.jfrog.io/artifactory/api/nuget/v3/mathtone-dev --name Artifactory --username ${ARTIFACTORY_USER} --password ${ARTIFACTORY_PWD} --store-password-in-clear-text
      - run:
          name: "Pack & Publish Chex"
          command: |
            dotnet pack src/Chex/Chex.csproj --configuration Release --version-suffix << parameters.suffix >> --output NugetPackages
            dotnet nuget push NugetPackages/Chex.0.0.0-alpha.nupkg --source Artifactory
      - run:
          name: "Pack & Publish Chex.Testing"
          command: |
            dotnet add src/Chex.Testing/Chex.Testing.csproj package Chex --source Artifactory --interactive -v 0.0.0-alpha
            dotnet pack src/Chex.Testing/Chex.Testing.csproj --configuration Release --version-suffix << parameters.suffix >> --output NugetPackages
            dotnet nuget push NugetPackages/Chex.Testing.0.0.0-alpha.nupkg --source Artifactory
            
      # - run:
      #     name: "Publish"
          

  #  docker: 
  #    - image: mcr.microsoft.com/dotnet/sdk:6.0
  #  parameters:
  #    suffix:
  #      type: string
  #  steps: # steps that comprise the `build` job
  #    - attach_workspace:
  #        at: .
  #    - run:
  #         name: "Pack Nuget Files"
  #         command: dotnet pack src/chex.sln --configuration Release --no-build << parameters.suffix >> --output NugetPackages
  #    - persist_to_workspace:
  #        root: .
  #        paths:
  #          - ./NugetPackages
  #ship:
  #  docker: 
  #    - image: mcr.microsoft.com/dotnet/sdk:6.0
  #  parameters:
  #    suffix:
  #      type: string
  #  steps:
  #    - attach_workspace:
  #        at: .
  #    - run: dotnet nuget push NugetPackages/Chex.0.0.0<< parameters.suffix >>.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
  #    - run: dotnet nuget push NugetPackages/Chex.Testing.0.0.0<< parameters.suffix >>.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
  #    - run: dotnet nuget push NugetPackages/Chex.Testing.Xunit.0.0.0<< parameters.suffix >>.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
          
workflows:
  build:
    jobs:
      - checkout:
          context: MATHTONE_DEV
      - remove-refs:
          context: MATHTONE_DEV
          requires:
            - checkout
      - pack-and-publish:
          context: MATHTONE_DEV
          suffix: alpha
          requires:
            - remove-refs
      #- pack:
      #    name: "Pack Alpha"
      #    context: MATHTONE_DEV
      #    suffix: --version-suffix alpha
      #    requires:
      #      - build
      #- pack:
      #    name: "Pack Release"
      #    context: MATHTONE_DEV
      #    suffix: ""
      #    requires:
      #      - build
      #- ship:
      #    name: "Ship Alpha"
      #    context: MATHTONE_DEV
      #    suffix: -alpha
      #    requires:
      #      - Pack Alpha
      #- approve-release:
      #    type: approval
      #    requires:
      #      - Pack Release
      #- ship:
      #    name: "Ship Release"
      #    context: MATHTONE_DEV
      #    suffix: ""
      #    requires:
      #      - approve-release