version: 2.1
orbs:
  win: circleci/windows@5
jobs: # basic units of work in a run
  checkup:
    docker: # use the Docker executor
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "Create Workspace"
          command: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - echo-output
  build:
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "Create Workspace"
          command: "mkdir -p workspace"
      - run:
          name: "Install project dependencies"
          command: dotnet restore src/chex.sln
      - run:
          name: "Build Project"
          command: dotnet build src/chex.sln --configuration Release
      - run:
          name: "Pack Nuget Files"
          command: dotnet pack src/chex.sln --configuration Release --no-build --version-suffix alpha --output NugetPackages
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - echo-output
  deploy:
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: "workspace"
      - run:
          command: echo "HI"
workflows: # a single workflow with a single job called build
  build:
    jobs:
      - checkup
      # - build:
      #     context: Testing-Env-Vars
      # - deploy:
      #     requires:
      #       - "build"

      