version: 2.1
commands:
  swapref:
    parameters:
      proj:
        type:
          string
      ref:
        type:
          string
      pkg:
        type:
          string
      version:
        type:
          string
    steps:
      - run: dotnet remove << parameters.proj >> reference << parameters.ref >>
      - run: dotnet add << parameters.proj >> package << parameters.pkg >> -v << parameters.version >> --source ~/project/packages
  pack-pre:
    parameters:
      project:
        type:
          string
      suffix:
        type:
          string
      version:
        type:
          string
    steps:
      - run:
          name: Build and Pack << parameters.project >>
          command: |
            dotnet build << parameters.project >> --configuration Release /p:VersionPrefix=<< parameters.version >>
            dotnet pack << parameters.project >> --configuration Release --no-build --output packages --version-suffix << parameters.suffix >> 
  pack-release:
    parameters:
      project:
        type:
          string
      version:
        type:
          string
    steps:
      - run:
          name: Build and Pack << parameters.project >>
          command: |
            dotnet build << parameters.project >> --configuration Release
            dotnet pack << parameters.project >> --configuration Release --no-build --output packages
  
jobs:
  checkout:
    description: Setup and run application tests
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore src/chex.sln

      - run:
          name: "Add Artifactory"
          command: dotnet nuget add source https://mathtone.jfrog.io/artifactory/api/nuget/v3/mathtone-dev --name Mathtone-Dev --username ${ARTIFACTORY_USER} --password ${ARTIFACTORY_PWD} --store-password-in-clear-text
      - run: dotnet nuget push packages/*.nupkg --source Mathtone-Dev
  publish-release-nuget:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: .
      - run: dotnet nuget push packages/*.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
workflows:
  build:
    jobs:
      - checkout