version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - run: ${TEST_VAR}
      - checkout
      
      - run:
          name: "Build Project"
          command: dotnet build src/chex.sln --configuration Release
      - persist_to_workspace:
          root: .
          paths:
            - .
  pack:
    docker: 
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    parameters:
      suffix:
        type: string
    steps: # steps that comprise the `build` job
      - attach_workspace:
          at: .
      - run:
           name: "Pack Nuget Files"
           command: dotnet pack src/chex.sln --configuration Release --no-build << parameters.suffix >> --output NugetPackages
      - persist_to_workspace:
          root: .
          paths:
            - ./NugetPackages
  ship:
    docker: 
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: .
      - run: ${TEST_VAR}
          
      - run:
          command: dotnet nuget push NugetPackages/Chex.0.0.0-alpha.nupkg --api-key $NUGET_PUBLISH_KEY --source https://api.nuget.org/v3/index.json
workflows:
  build:
    jobs:
      - build:
          context: MATHTONE_DEV
      - pack:
          name: "Pack Alpha"
          context: MATHTONE_DEV
          suffix: --version-suffix alpha
          requires:
            - build
      - pack:
          name: "Pack Release"
          context: MATHTONE_DEV
          suffix: ""
          requires:
            - build
      - ship:
          name: "Ship Alpha"
          context: MATHTONE_DEV          
          requires:
            - Pack Alpha