version: 2.1
orbs:
  win: circleci/windows@5
jobs: # basic units of work in a run
  build:
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "Install project dependencies"
          command: dotnet restore src/chex.sln
      - run:
          name: "Build Project"
          command: dotnet build src/chex.sln --configuration Release
      - run:
          name: "Pack Nuget Files"
          command: dotnet pack src/chex.sln --configuration Release --no-build --version-suffix alpha
workflows: # a single workflow with a single job called build
  build:
    jobs:
      - build:
          context: Testing-Env-Vars
