version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps: 
      - checkout
      - run:
          name: "Build Project"
          command: dotnet build src/chex.sln --configuration Release
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  build:
    jobs:
      - build:
          context: MATHTONE_DEV