version: 2.1
jobs:
  checkout:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  remove-refs:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Remove Project Refs"
          command: |
            cd src/Chex.Testing
            dotnet remove reference ../Chex/Chex.csproj
            cd ../Chex.Testing.Xunit
            dotnet remove reference ../Chex/ChexTesting.csproj
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - .
  pack-and-publish-alpha:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    parameters:
      suffix :
        type:  string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Add Nuget & Artifactory to Nuget Sources"
          command: |
            dotnet nuget add source https://api.nuget.org/v3/index.json --name Nuget
            dotnet nuget add source https://mathtone.jfrog.io/artifactory/api/nuget/v3/mathtone-dev --name Mathtone-Dev --username ${ARTIFACTORY_USER} --password ${ARTIFACTORY_PWD} --store-password-in-clear-text
      - run:
          name: "Pack & Publish Chex"
          command: |
            dotnet pack src/Chex/Chex.csproj --configuration Release --version-suffix << parameters.suffix >> --output NugetPackages/Chex
            dotnet nuget push NugetPackages/Chex/Chex.*-alpha.nupkg --source Mathtone-Dev
      - run:
          name: "Pack & Publish Chex.Testing"
          command: |
            dotnet add src/Chex.Testing/Chex.Testing.csproj package Chex --source https://mathtone.jfrog.io/artifactory/api/nuget/v3/mathtone-dev -v 0.0.0-alpha
            dotnet pack src/Chex.Testing/Chex.Testing.csproj --configuration Release --version-suffix alpha --output NugetPackages/Chex.Testing
            dotnet nuget push NugetPackages/Chex.Testing/Chex.Testing.*-alpha.nupkg --source Mathtone-Dev
      - run:
          name: "Pack & Publish Chex.Testing.Xunit"
          command: |
            dotnet add src/Chex.Testing.Xunit/Chex.Testing.Xunit.csproj package Chex --source https://mathtone.jfrog.io/artifactory/api/nuget/v3/mathtone-dev -v 0.0.0-alpha
            dotnet pack src/Chex.Testing.Xunit/Chex.Testing.Xunit.csproj --configuration Release --version-suffix alpha --output NugetPackages/Chex.Testing.Xunit
            dotnet nuget push NugetPackages/Chex.Testing.Xunit/Chex.Testing.Xunit.*-alpha.nupkg --source Mathtone-Dev
      - persist_to_workspace:
          root: .
          paths:
            - .
  pack-and-publish-alpha-release:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    parameters:
      suffix :
        type:  string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Pack & Publish Chex"
          command: |
            dotnet pack src/Chex/Chex.csproj --configuration Release --version-suffix << parameters.suffix >> --output NugetPackages
            dotnet nuget push NugetPackages/Chex.*-alpha.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
      - run:
          name: "Pack & Publish Chex.Testing"
          command: |
            dotnet add src/Chex.Testing/Chex.Testing.csproj package Chex --source https://api.nuget.org/v3/index.json -v 0.0.0-alpha
            dotnet pack src/Chex.Testing/Chex.Testing.csproj --configuration Release --version-suffix alpha --output NugetPackages
            dotnet nuget push NugetPackages/Chex.Testing.*-alpha.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
      - run:
          name: "Pack & Publish Chex.Testing.Xunit"
          command: |
            dotnet add src/Chex.Testing.Xunit/Chex.Testing.Xunit.csproj package Chex --source https://api.nuget.org/v3/index.json -v 0.0.0-alpha
            dotnet pack src/Chex.Testing.Xunit/Chex.Testing.Xunit.csproj --configuration Release --version-suffix alpha --output NugetPackages
            dotnet nuget push NugetPackages/Chex.Testing.Xunit.*-alpha.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
  publish-final-release:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Pack & Publish Chex"
          command: |
            dotnet pack src/Chex/Chex.csproj --configuration Release --output NugetPackages
            dotnet nuget push NugetPackages/Chex.*.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
      - run:
          name: "Pack & Publish Chex.Testing"
          command: |
            dotnet add src/Chex.Testing/Chex.Testing.csproj package Chex --source https://api.nuget.org/v3/index.json -v 0.0.0
            dotnet pack src/Chex.Testing/Chex.Testing.csproj --configuration Release --output NugetPackages
            dotnet nuget push NugetPackages/Chex.Testing.*.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
      - run:
          name: "Pack & Publish Chex.Testing.Xunit"
          command: |
            dotnet add src/Chex.Testing.Xunit/Chex.Testing.Xunit.csproj package Chex --source https://api.nuget.org/v3/index.json -v 0.0.0
            dotnet pack src/Chex.Testing.Xunit/Chex.Testing.Xunit.csproj --configuration Release --output NugetPackages
            dotnet nuget push NugetPackages/Chex.Testing.Xunit.*.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
workflows:
  build:
    jobs:
      - checkout:
          context: MATHTONE_DEV
      - remove-refs:
          context: MATHTONE_DEV
          requires:
            - checkout
      - pack-and-publish-alpha:
          context: MATHTONE_DEV
          suffix: alpha
          requires:
            - remove-refs
      - request-release-alpha:
          type: approval
          requires:
            - pack-and-publish-alpha
      - request-release:
          type: approval
          requires:
            - pack-and-publish-alpha
      - pack-and-publish-alpha-release:
          context: MATHTONE_DEV
          suffix: alpha
          requires:
            - request-release-alpha
      - publish-final-release:
          filters:
            branches:
              only:
                - main
          context: MATHTONE_DEV
          requires:
            - request-release
